base_url = "https://yudaniel.com"

title = "daniel yu"

description = "A collection of my thoughts about science, art, and living."

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author.name = "Daniel Yu"
