# config.toml

title = "daniel yu"
base_url = "https://yudaniel.com"
description = "A collection of my thoughts about science, art, and life."
author = "Daniel Yu"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"
