base_url = "danielyu2003.github.io"

title = "Coding With Y{o}u"

description = "Welcome to my blog! Let's learn about software, systems, and embedded technology."

[extra]
author.name = "Daniel Yu"
site_name = "Coding With Y{o}u"