base_url = "https://blog.danielyu.us"

title = "Choropleb"

description = "A portrait of a dilettante."

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author.name = "Daniel Yu"
site_name = "Choropleb"
