base_url = "https://blog.danielyu.us"

title = "Coding with Y{o}u"

description = "A history of my thoughts and activities in software development."

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author.name = "Daniel Yu"
site_name = "c.w.y"