base_url = "https://blog.danielyu.us"

title = "The Cybernetic Nomad"

description = "Essays on software/systems, tooling, and cybernetics."

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author.name = "Daniel Yu"
site_name = "The Cybernetic Nomad"