base_url = "https://blog.danielyu.us"

title = "Daniel Yu"

description = "Daniel Yu's Blog"

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author.name = "Daniel Yu"
site_name = "Daniel Yu"
