base_url = "https://blog.danielyu.us"

title = "Coding with Y{o}u"

description = "A history of my thoughts and activities in software development."

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author.name = "Daniel Yu"
site_name = "c.w.y"
