base_url = "https://yudaniel.com"

title = "daniel yu"

description = "My personal blog about science and humanity."

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author.name = "Daniel Yu"
site_name = "daniel yu"
